'use strict'
gulp = require('gulp')
paths = gulp.paths
$ = require('gulp-load-plugins')(pattern: [
  'gulp-*'
  'main-bower-files'
  'uglify-save-license'
  'del'
])
gulp.task 'partials', ->
  gulp.src([
    paths.src + '/{app,components}/**/*.html'
    paths.tmp + '/{app,components}/**/*.html'
  ]).pipe($.minifyHtml(
    empty: true
    spare: true
    quotes: true)).pipe($.angularTemplatecache('templateCacheHtml.js', module: 'ri')).pipe gulp.dest(paths.tmp + '/partials/')
gulp.task 'html', [
  'inject'
  'partials'
], ->
  partialsInjectFile = gulp.src(paths.tmp + '/partials/templateCacheHtml.js', read: false)
  partialsInjectOptions =
    starttag: '<!-- inject:partials -->'
    ignorePath: paths.tmp + '/partials'
    addRootSlash: false
  htmlFilter = $.filter('*.html')
  jsFilter = $.filter('**/*.js')
  cssFilter = $.filter('**/*.css')
  assets = undefined
  gulp.src(paths.tmp + '/serve/*.html').pipe($.inject(partialsInjectFile, partialsInjectOptions)).pipe(assets = $.useref.assets()).pipe($.rev()).pipe(jsFilter).pipe($.ngAnnotate()).pipe($.uglify(preserveComments: $.uglifySaveLicense)).pipe(jsFilter.restore()).pipe(cssFilter).pipe($.csso()).pipe(cssFilter.restore()).pipe(assets.restore()).pipe($.useref()).pipe($.revReplace()).pipe(htmlFilter).pipe($.minifyHtml(
    empty: true
    spare: true
    quotes: true)).pipe(htmlFilter.restore()).pipe(gulp.dest(paths.dist + '/')).pipe $.size(
    title: paths.dist + '/'
    showFiles: true)
gulp.task 'assets', ->
  gulp.src(paths.src + '/assets/**/*').pipe gulp.dest(paths.dist + '/assets/')
gulp.task 'foundation-fonts', ->
  gulp.src('./bower_components/foundation-icon-fonts/**/*')
    .pipe gulp.dest(paths.dist + '/bower_components/foundation-icon-fonts/')
gulp.task 'misc', ->
  gulp.src(paths.src + '/**/*.ico').pipe gulp.dest(paths.dist + '/')
gulp.task 'clean', (done) ->
  $.del [
    paths.dist + '/'
    paths.tmp + '/'
  ], done
  return
gulp.task 'build', [
  'html'
  'assets'
  'foundation-fonts'
  'misc'
]

# ---
# generated by js2coffee 2.0.1
